### ISSUE TITLE
Add German Translation

### ISSUE THREAD

**Issue by petejoybaker** [enterpriseWifiSafeguard/EnterpriseWifiSafeguard#13]
Please add a German translation e.g. for eduroam users.

**Comment by petejoybaker** [comment]
I will help.

**Comment by xamor** [comment]
I think this could be helpfull: http://stackoverflow.com/questions/4259128/how-can-i-create-a-multilingual-android-application

**Comment by xamor** [comment]
Done in 4115a322ef57f7d6a6637942f435575e22502421
