### ISSUE TITLE
Create Logo/Icon

### ISSUE THREAD

**Issue by 85pando** [enterpriseWifiSafeguard/EnterpriseWifiSafeguard#15]
Before release, it should have a Logo/Icon for better recognizability.

**Comment by xamor** [comment]
Fixed in 83b3b8030519b67b5d93b487469f0c327f63a32

**Comment by petejoybaker** [comment]
Icons from the Numix Project (GPL, https://github.com/numixproject):
![ews-circle](https://cloud.githubusercontent.com/assets/13995406/9656033/a536a2ae-5235-11e5-938a-acee67793891.png)
![ews-square](https://cloud.githubusercontent.com/assets/13995406/9656036/a90d42f2-5235-11e5-9aab-50c47e544e83.png)
